/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "index": {
        "System": {
            "DEFAULT": string;
            "OperationSuccess": string;
            "OperationFailed": string;
            "SERVER_ERROR": string;
            "ThirdPartyApiRequestFailed": string;
        };
        "Request": {
            "TOO_MANY_REQUESTS": string;
            "REQUEST_INVALIDATED": string;
            "RequestTimeout": string;
        };
        "WebSocket": {
            "WebSocketDisconnected": string;
            "WebSocketConnected": string;
        };
        "Auth": {
            "DemoModeOperationNotAllowed": string;
            "AuthenticationFailed": string;
            "INVALID_LOGIN": string;
            "NO_PERMISSION": string;
            "ONLY_ADMIN_CAN_LOGIN": string;
            "ACCOUNT_LOGGED_IN_ELSEWHERE": string;
            "GUEST_ACCOUNT_RESTRICTED_OPERATION": string;
            "NO_LOGIN": string;
            "SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED": string;
        };
        "Dto": {
            "RoleValueLengthTooShort": string;
            "RoleValueAlphanumericOnly": string;
            "RoleNameLengthTooShort": string;
            "CronExpressionRequired": string;
            "InvalidPhoneNumberFormat": string;
            "InvalidEmailFormat": string;
            "InvalidIdFormat": string;
        };
        "Unique": {
            "SYSTEM_USER_EXISTS": string;
            "NODE_ROUTE_EXISTS": string;
            "DuplicateRecordExists": string;
            "KeyNameAlreadyExists": string;
            "DuplicateDictionaryName": string;
            "DuplicateEnglishDictionaryName": string;
            "DuplicateDictionaryCode": string;
            "DuplicateDictionaryItemName": string;
            "DuplicateEnglishDictionaryItemName": string;
            "DuplicateDictionaryItemCode": string;
            "DuplicateDeviceAliasOrSN": string;
            "TableNameExists": string;
            "DuplicateChannelNumber": string;
            "UniqueAliasRequired": string;
            "DuplicateNetworkTemplateName": string;
            "DuplicateSMSContent": string;
            "DuplicateTaskTemplateName": string;
            "DuplicateSubtaskName": string;
            "UniqueDictionaryKeyValueRequired": string;
            "DuplicateTaskName": string;
        };
        "DataLint": {
            "ROLE_HAS_ASSOCIATED_USERS": string;
            "DEPARTMENT_HAS_ASSOCIATED_USERS": string;
            "DEPARTMENT_HAS_ASSOCIATED_ROLES": string;
            "DEPARTMENT_HAS_CHILD_DEPARTMENTS": string;
            "MenuHasAssociatedRoles": string;
            "RoleHasAssociatedUsers": string;
        };
        "Exist": {
            "RecordNotFound": string;
            "EXECUTED_MISSION_NOT_FOUND": string;
            "MISSION_NOT_FOUND": string;
            "TaskNotFoundById": string;
            "ScheduledTaskNotFound": string;
            "REQUESTED_RESOURCE_NOT_FOUND": string;
            "DEFAULT_ROLE_NOT_FOUND": string;
            "DEPARTMENT_NOT_FOUND": string;
            "USER_NOT_FOUND": string;
            "UNABLE_TO_FIND_DEPARTMENT_FOR_USER": string;
            "PARENT_MENU_NOT_FOUND": string;
            "HFTableNameNotExists": string;
            "TypeNoLongerExists": string;
            "PARAMETER_CONFIG_KEY_EXISTS": string;
        };
        "Task": {
            "INSECURE_MISSION": string;
            "MISSION_EXECUTION_FAILED": string;
            "ScheduledTaskParametersMissing": string;
            "EmailTaskParametersMissing": string;
            "HttpRequestTaskParametersMissing": string;
        };
        "File": {
            "InvalidFileType": string;
            "UploadFailed": string;
        };
        "Email": {
            "VERIFICATION_CODE_SEND_FAILED": string;
            "MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY": string;
            "VerificationCode": string;
            "EmailTaskParametersMissing": string;
        };
        "Login": {
            "INVALID_VERIFICATION_CODE": string;
            "INVALID_USERNAME_PASSWORD": string;
        };
        "USER": {
            "PASSWORD_MISMATCH": string;
            "LOGOUT_OWN_SESSION": string;
            "NOT_ALLOWED_TO_LOGOUT_USER": string;
            "CannotDeleteRootUser": string;
            "UsernameFailed": string;
            "InvalidPasswordFormat": string;
            "PasswordRequirements": string;
        };
        "Role": {
            "CannotDeleteSuperAdmin": string;
        };
        "Menu": {
            "ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE": string;
            "ILLEGAL_OPERATION_DIRECTORY_PARENT": string;
            "PERMISSION_REQUIRES_PARENT": string;
        };
        "Dict": {
            "InvalidDictionaryFieldValue": string;
            "OperationFailedDictionaryOrParameterError": string;
        };
        "ShotMessage": {
            "SystemDataLimitReached": string;
        };
        "HopFreq": {
            "DataLimitExceeded": string;
        };
        "NoExist": {
            "RecordNotFound": string;
            "EXECUTED_MISSION_NOT_FOUND": string;
            "MISSION_NOT_FOUND": string;
            "TaskNotFoundById": string;
            "ScheduledTaskNotFound": string;
            "REQUESTED_RESOURCE_NOT_FOUND": string;
            "DEFAULT_ROLE_NOT_FOUND": string;
            "DEPARTMENT_NOT_FOUND": string;
            "USER_NOT_FOUND": string;
            "UNABLE_TO_FIND_DEPARTMENT_FOR_USER": string;
            "PARENT_MENU_NOT_FOUND": string;
            "HFTableNameNotExists": string;
            "TypeNoLongerExists": string;
            "PARAMETER_CONFIG_KEY_EXISTS": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
