export enum ErrorEnum {
  // ! Common
  DEFAULT = '0:Unknown error',
  OperationFailed = "Operation failed",
  SERVER_ERROR = '500:Service unavailable, please try again later',

  // ! Core Business Logic
  SYSTEM_USER_EXISTS = '1001:System user already exists',
  INVALID_VERIFICATION_CODE = '1002:Invalid verification code',
  INVALID_USERNAME_PASSWORD = '1003:Invalid credentials',
  NODE_ROUTE_EXISTS = '1004:Node route already exists',
  PERMISSION_REQUIRES_PARENT = '1005:Permission requires parent node',
  ILLEGAL_OPERATION_DIRECTORY_PARENT = '1006:Invalid operation: only directory-type parent nodes allowed',
  ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '1007:Illegal node type conversion',
  ROLE_HAS_ASSOCIATED_USERS = '1008:Cannot delete role with associated users',
  DEPARTMENT_HAS_ASSOCIATED_USERS = '1009:Cannot delete department with associated users',
  DEPARTMENT_HAS_ASSOCIATED_ROLES = '1010:Cannot delete department with associated roles',
  PASSWORD_MISMATCH = '1011:Old password does not match',
  LOGOUT_OWN_SESSION = '1012:Use logout button to terminate current session',
  NOT_ALLOWED_TO_LOGOUT_USER = '1013:Unauthorized to log out this user',
  PARENT_MENU_NOT_FOUND = '1014:Parent menu not found',
  DEPARTMENT_HAS_CHILD_DEPARTMENTS = '1015:Cannot delete department with child departments',
  SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '1016:System built-in feature is read-only',
  USER_NOT_FOUND = '1017:User not found',
  UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '1018:Cannot locate user department',
  DEPARTMENT_NOT_FOUND = '1019:Department not found',
  PARAMETER_CONFIG_KEY_EXISTS = '1022:Configuration key already exists',
  DEFAULT_ROLE_NOT_FOUND = '1023:Default assigned role not found',

  // ! Authentication & Authorization
  INVALID_LOGIN = '1101:Session expired, please relogin',
  NO_PERMISSION = '1102:Access denied',
  ONLY_ADMIN_CAN_LOGIN = '1103:Admin privileges required',
  REQUEST_INVALIDATED = '1104:Request has expired',
  ACCOUNT_LOGGED_IN_ELSEWHERE = '1105:Account logged in elsewhere',
  GUEST_ACCOUNT_RESTRICTED_OPERATION = '1106:Guest account operation prohibited',
  REQUESTED_RESOURCE_NOT_FOUND = '1107:Requested resource unavailable',
  NO_LOGIN = '1108:Authentication required',

  // ! Rate Limiting
  TOO_MANY_REQUESTS = '1201:Request limit exceeded, try again in 1 minute',
  MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '1202:Maximum 5 verification codes per day',
  VERIFICATION_CODE_SEND_FAILED = '1203:Failed to send verification code',

  // ! System Tasks
  INSECURE_MISSION = '1301:Unsecured task - requires @Mission annotation',
  EXECUTED_MISSION_NOT_FOUND = '1302:Scheduled task not found',
  MISSION_EXECUTION_FAILED = '1303:Task execution failed',
  MISSION_NOT_FOUND = '1304:Task does not exist',

  // ! Specific Business Logic
  AuthenticationFailed = "Authentication failed",
  DuplicateRecordExists = "Duplicate record detected",
  InvalidPasswordFormat = "Invalid password format",
  PasswordRequirements = "Password must contain letters and numbers (6-16 characters)",
  CannotDeleteRootUser = "Root user deletion prohibited",
  CannotDeleteSuperAdmin = "Super admin deletion prohibited",
  RoleValueLengthTooShort = "Role value requires minimum 2 characters",
  RoleValueAlphanumericOnly = "Role value allows alphanumeric only",
  RoleNameLengthTooShort = "Role name requires minimum 2 characters",
  RoleHasAssociatedUsers = "Role has associated users, deletion prohibited",
  KeyNameAlreadyExists = "Key name already exists",
  MenuHasAssociatedRoles = "Menu has associated roles, deletion prohibited",
  DictionaryNotRepeatable = "Dictionary entries must be unique",
  DuplicateDictionaryName = "Duplicate dictionary name detected",
  DuplicateEnglishDictionaryName = "Duplicate English dictionary name",
  DuplicateDictionaryCode = "Duplicate dictionary code detected",
  DuplicateDictionaryItemName = "Duplicate dictionary item name",
  DuplicateEnglishDictionaryItemName = "Duplicate English dictionary item name",
  DuplicateDictionaryItemCode = "Duplicate dictionary item code",
  RecordNotFound = "Record not found",
  RequestTimeout = "Request timed out",
  DuplicateDeviceAliasOrSN = "Duplicate device alias/SN detected",
  DictionaryMissingFields = "Missing dictionary fields: device_type, model, status",
  TableNameExists = "Table name already exists",
  DuplicateChannelNumber = "Duplicate channel number detected",
  DataLimitExceeded = "Data limit exceeded (80 entries), please cleanup",
  UniqueAliasRequired = "Alias must be unique",
  TypeNoLongerExists = "Selected type is invalid or deprecated",
  DuplicateNetworkTemplateName = "Duplicate network template name",
  DuplicateSMSContent = "Duplicate SMS content detected",
  SystemDataLimitReached = "System data limit reached (100 entries)",
  DuplicateTaskTemplateName = "Duplicate task template name",
  DuplicateSubtaskName = "Duplicate subtask name detected",
  InvalidDictionaryFieldValue = "Invalid dictionary field value",
  UniqueDictionaryKeyValueRequired = "Dictionary key/value must be unique",
  DuplicateKeyName = "Duplicate key name detected",
  DuplicateTaskName = "Duplicate task name detected",
  CronExpressionRequired = "Cron expression required",
  TaskNotFoundById = "Task not found with given ID",
  ScheduledTaskParametersMissing = "Missing scheduled task parameters",
  ScheduledTaskNotFound = "Scheduled task not found",
  EmailTaskParametersMissing = "Missing email task parameters",
  HttpRequestTaskParametersMissing = "Missing HTTP request parameters",
  OperationFailedDictionaryOrParameterError = "Operation failed: invalid dictionary or parameters",

  // ! Middleware
  InternalIP = "Internal IP address",
  ThirdPartyApiRequestFailed = "Third-party API request failed",
  DemoModeOperationNotAllowed = "Operation prohibited in demo mode",
  WebSocketDisconnected = "WebSocket disconnected",
  WebSocketConnected = "WebSocket connected",
  ReceiveEvent = "Event received:",
  PublishEvent = "Event published:",
  VerificationCode = "Verification code",
  DeleteExpired = "Expired items deleted",
  IssuedAt = "Issued at",
  Deleted = "Deleted",
  ExpiredItemsCleared = "Expired items cleared",
  StartScanningClearExpired = "Initiating expired data cleanup",
  TaskNotFound = "Task not found",
  Closed = "Connection closed",
  Response = "Response",
  Request = "Request",

  // ! Temporary Exclusions
  InvalidFileType = "Invalid file type",
  UploadFailed = "Upload failed",
  InvalidPhoneNumberFormat = "Invalid phone number format",
  InvalidEmailFormat = "Invalid email format"
}