export enum ErrorEnum {
  // ! Common
  DEFAULT = '0:Unknown error',
  OperationFailed = "Operation failed",
  SERVER_ERROR = '500:Service unavailable, please try again later',

  // ! Core Business Logic
  SYSTEM_USER_EXISTS = '1001:System user already exists',
  INVALID_VERIFICATION_CODE = '1002:Invalid verification code',
  INVALID_USERNAME_PASSWORD = '1003:Invalid username or password',
  NODE_ROUTE_EXISTS = '1004:Node route already exists',
  PERMISSION_REQUIRES_PARENT = '1005:Permission requires parent node',
  ILLEGAL_OPERATION_DIRECTORY_PARENT = '1006:Invalid operation: only directory-type parent nodes allowed',
  ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '1007:Illegal operation: node type conversion not supported',
  ROLE_HAS_ASSOCIATED_USERS = '1008:Role contains associated users, remove associations first',
  DEPARTMENT_HAS_ASSOCIATED_USERS = '1009:Department contains users, remove users first',
  DEPARTMENT_HAS_ASSOCIATED_ROLES = '1010:Department contains roles, remove roles first',
  PASSWORD_MISMATCH = '1011:Old password does not match records',
  LOGOUT_OWN_SESSION = '1012:To terminate current session, please logout via top-right menu',
  NOT_ALLOWED_TO_LOGOUT_USER = '1013:Unauthorized to terminate this user session',
  PARENT_MENU_NOT_FOUND = '1014:Parent menu not found',
  DEPARTMENT_HAS_CHILD_DEPARTMENTS = '1015:Department contains sub-departments, remove them first',
  SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '1016:System built-in features are read-only',
  USER_NOT_FOUND = '1017:User not found',
  UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '1018:Cannot locate user department',
  DEPARTMENT_NOT_FOUND = '1019:Department not found',
  PARAMETER_CONFIG_KEY_EXISTS = '1022:Configuration key already exists',
  DEFAULT_ROLE_NOT_FOUND = '1023:Default assigned role not found',

  // ! Authentication & Authorization
  INVALID_LOGIN = '1101:Session expired, please relogin',
  NO_PERMISSION = '1102:Access denied: insufficient privileges',
  ONLY_ADMIN_CAN_LOGIN = '1103:Admin privileges required for login',
  REQUEST_INVALIDATED = '1104:Request has expired',
  ACCOUNT_LOGGED_IN_ELSEWHERE = '1105:Account logged in elsewhere',
  GUEST_ACCOUNT_RESTRICTED_OPERATION = '1106:Guest account operations disabled',
  REQUESTED_RESOURCE_NOT_FOUND = '1107:Requested resource not found',
  NO_LOGIN = '1108:Authentication required, please login',

  // ! Rate Limiting
  TOO_MANY_REQUESTS = '1201:Request throttled, try again in 60 seconds',
  MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '1202:Verification code limit exceeded (5/day)',
  VERIFICATION_CODE_SEND_FAILED = '1203:Failed to send verification code',

  // ! Task System
  INSECURE_MISSION = '1301:Unsecured task execution detected',
  EXECUTED_MISSION_NOT_FOUND = '1302:Scheduled task not found',
  MISSION_EXECUTION_FAILED = '1303:Task execution failed',
  MISSION_NOT_FOUND = '1304:Task does not exist',

  // ! Domain-Specific Business Logic
  AuthenticationFailed = "Authentication failed",
  DuplicateRecordExists = "Duplicate record detected",
  InvalidPasswordFormat = "Invalid password format",
  PasswordRequirements = "Password must contain 6-16 characters with letters and numbers",
  CannotDeleteRootUser = "Root user deletion prohibited",
  CannotDeleteSuperAdmin = "Super admin deletion restricted",
  RoleValueLengthTooShort = "Role value requires minimum 2 characters",
  RoleValueAlphanumericOnly = "Role value must be alphanumeric",
  RoleNameLengthTooShort = "Role name requires minimum 2 characters",
  KeyNameAlreadyExists = "Key name already exists",
  MenuHasAssociatedRoles = "Menu contains role associations, remove first",
  DictionaryNotRepeatable = "Dictionary entries must be unique",
  DuplicateDictionaryName = "Duplicate dictionary name",
  DuplicateDictionaryItemName = "Duplicate dictionary item name",
  DuplicateEnglishDictionaryName = "Duplicate English dictionary name", 
  DuplicateEnglishDictionaryItemName = "Duplicate English dictionary item",
  DuplicateDictionaryCode = "Duplicate dictionary code",
  DuplicateDictionaryItemCode = "Duplicate dictionary item code",
  RecordNotFound = "Record not found",
  RequestTimeout = "Request timeout",
  DuplicateDeviceAliasOrSN = "Duplicate device alias or SN",
  DictionaryMissingFields = "Required dictionary fields missing: device_type, model, status",
  TableNameExists = "Table name already exists",
  DuplicateChannelNumber = "Duplicate channel number",
  DataLimitExceeded = "Data limit exceeded (80 entries), please clean up",
  UniqueAliasRequired = "Alias must be unique",
  TypeNoLongerExists = "Selected type no longer available, please refresh",
  DuplicateNetworkTemplateName = "Duplicate network template name",
  DuplicateSMSContent = "Duplicate SMS content detected",
  SystemDataLimitReached = "System data limit reached (100 entries)",
  DuplicateTaskTemplateName = "Duplicate task template name",
  DuplicateSubtaskName = "Duplicate subtask name",
  InvalidDictionaryFieldValue = "Invalid dictionary field value",
  UniqueDictionaryKeyValueRequired = "Dictionary key-value pairs must be unique",
  DuplicateTaskName = "Duplicate task name",
  CronExpressionRequired = "Cron expression required",
  TaskNotFoundById = "Task not found with specified ID",
  ScheduledTaskParametersMissing = "Scheduled task parameters missing",
  ScheduledTaskNotFound = "Scheduled task not found",
  EmailTaskParametersMissing = "Email task parameters incomplete",
  HttpRequestTaskParametersMissing = "HTTP request parameters incomplete",
  OperationFailedDictionaryOrParameterError = "Operation failed: verify dictionary existence or parameters",

  // ! Infrastructure Components
  InternalIP = "Internal network IP",
  ThirdPartyApiRequestFailed = "Third-party API request failed",
  DemoModeOperationNotAllowed = "Operation disabled in demo mode",
  WebSocketDisconnected = "WebSocket connection lost",
  WebSocketConnected = "WebSocket connected",
  ReceiveEvent = "Event received:",
  PublishEvent = "Event published:",
  VerificationCode = "Verification code",
  DeleteExpired = "Expired records deletion initiated",
  IssuedAt = "Issued at",
  Deleted = "Deleted",
  ExpiredItemsCleared = "expired items cleared",
  StartScanningClearExpired = "Starting scheduled cleanup of expired records",
  Closed = "Connection closed",
  Response = "Response",
  Request = "Request",

  // ! File Handling
  InvalidFileType = "Invalid file type",
  UploadFailed = "Upload failed",
  InvalidPhoneNumberFormat = "Invalid phone number format",
  InvalidEmailFormat = "Invalid email format"
}